# https://github.com/repository-settings/app

# https://github.com/gitfool/.github/blob/main/.github/settings.yml
_extends: .github

repository:
  topics: devops, github-actions

branches:
  - name: main
    protection:
      required_status_checks:
        contexts:
          - build-docker
          - build-linux
          - build-mac
          - build-windows
