name: ci
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

env:
  Cake_Settings_EnableScriptCache: true
  Cake_Settings_ShowProcessCommandLine: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true
  DOTNET_ROLL_FORWARD: Major

jobs:
  build-docker:
    needs: [ build-linux, build-mac, build-windows ]
    runs-on: ubuntu-latest
    container: dockfool/cake-docker:latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
          filter: tree:0
          show-progress: false

      - name: Show contexts
        uses: actions/github-script@v6.4.1
        with:
          script: |
            // show contexts
            const contexts = {
              github: ${{ toJSON(github) }},
              runner: ${{ toJSON(runner) }},
              job: ${{ toJSON(job) }}
            };
            console.log(JSON.stringify(contexts, null, 2));

      - name: Cake build
        id: cake
        run: dotnet tool restore && dotnet cake --target=info --verbosity=verbose

      - name: Show outputs
        uses: actions/github-script@v6.4.1
        with:
          script: |
            // show outputs
            const json = ${{ steps.cake.outputs.json }};
            console.log("json:");
            console.log(JSON.stringify(json, null, 2));
            console.log("public: ${{ steps.cake.outputs.public }}");
            console.log("version: ${{ steps.cake.outputs.version }}");

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
          filter: tree:0
          show-progress: false

      - name: Show contexts
        uses: actions/github-script@v6.4.1
        with:
          script: |
            // show contexts
            const contexts = {
              github: ${{ toJSON(github) }},
              runner: ${{ toJSON(runner) }},
              job: ${{ toJSON(job) }}
            };
            console.log(JSON.stringify(contexts, null, 2));

      - name: Install dotnet
        uses: actions/setup-dotnet@v3.2.0
        with:
          # renovate: datasource=dotnet depName=dotnet-sdk
          dotnet-version: 7.0.404

      - name: Cake build
        id: cake
        run: dotnet tool restore && dotnet cake --target=info --verbosity=verbose

      - name: Show outputs
        uses: actions/github-script@v6.4.1
        with:
          script: |
            // show outputs
            const json = ${{ steps.cake.outputs.json }};
            console.log("json:");
            console.log(JSON.stringify(json, null, 2));
            console.log("public: ${{ steps.cake.outputs.public }}");
            console.log("version: ${{ steps.cake.outputs.version }}");

  build-mac:
    runs-on: macos-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
          filter: tree:0
          show-progress: false

      - name: Show contexts
        uses: actions/github-script@v6.4.1
        with:
          script: |
            // show contexts
            const contexts = {
              github: ${{ toJSON(github) }},
              runner: ${{ toJSON(runner) }},
              job: ${{ toJSON(job) }}
            };
            console.log(JSON.stringify(contexts, null, 2));

      - name: Install dotnet
        uses: actions/setup-dotnet@v3.2.0
        with:
          # renovate: datasource=dotnet depName=dotnet-sdk
          dotnet-version: 7.0.404

      - name: Cake build
        id: cake
        run: dotnet tool restore && dotnet cake --target=info --verbosity=verbose

      - name: Show outputs
        uses: actions/github-script@v6.4.1
        with:
          script: |
            // show outputs
            const json = ${{ steps.cake.outputs.json }};
            console.log("json:");
            console.log(JSON.stringify(json, null, 2));
            console.log("public: ${{ steps.cake.outputs.public }}");
            console.log("version: ${{ steps.cake.outputs.version }}");

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
          filter: tree:0
          show-progress: false

      - name: Show contexts
        uses: actions/github-script@v6.4.1
        with:
          script: |
            // show contexts
            const contexts = {
              github: ${{ toJSON(github) }},
              runner: ${{ toJSON(runner) }},
              job: ${{ toJSON(job) }}
            };
            console.log(JSON.stringify(contexts, null, 2));

      - name: Install dotnet
        uses: actions/setup-dotnet@v3.2.0
        with:
          # renovate: datasource=dotnet depName=dotnet-sdk
          dotnet-version: 7.0.404

      - name: Cake build
        id: cake
        run: dotnet tool restore && dotnet cake --target=info --verbosity=verbose

      - name: Show outputs
        uses: actions/github-script@v6.4.1
        with:
          script: |
            // show outputs
            const json = ${{ steps.cake.outputs.json }};
            console.log("json:");
            console.log(JSON.stringify(json, null, 2));
            console.log("public: ${{ steps.cake.outputs.public }}");
            console.log("version: ${{ steps.cake.outputs.version }}");
