name: ci
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

env:
  CAKE_SETTINGS_ENABLESCRIPTCACHE: true
  CAKE_SETTINGS_SHOWPROCESSCOMMANDLINE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true
  DOTNET_ROLL_FORWARD: Major

jobs:
  build-docker:
    needs: [ build-linux, build-mac, build-windows ]
    runs-on: ubuntu-latest
    container: dockfool/cake-docker:latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Show contexts
        uses: actions/github-script@v6.1.1
        with:
          script: |
            // show contexts
            const contexts = {
              github: ${{ toJSON(github) }},
              runner: ${{ toJSON(runner) }},
              job: ${{ toJSON(job) }}
            };
            console.log(JSON.stringify(contexts, null, 2));

      - name: Cake build
        run: dotnet tool restore && dotnet cake --target=info --verbosity=verbose

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Show contexts
        uses: actions/github-script@v6.1.1
        with:
          script: |
            // show contexts
            const contexts = {
              github: ${{ toJSON(github) }},
              runner: ${{ toJSON(runner) }},
              job: ${{ toJSON(job) }}
            };
            console.log(JSON.stringify(contexts, null, 2));

      - name: Install dotnet
        uses: actions/setup-dotnet@v2.1.0
        with:
          # renovate: datasource=docker depName=dotnet-sdk packageName=mcr.microsoft.com/dotnet/sdk
          dotnet-version: 6.0.400

      - name: Cake build
        run: dotnet tool restore && dotnet cake --target=info --verbosity=verbose

  build-mac:
    runs-on: macos-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Show contexts
        uses: actions/github-script@v6.1.1
        with:
          script: |
            // show contexts
            const contexts = {
              github: ${{ toJSON(github) }},
              runner: ${{ toJSON(runner) }},
              job: ${{ toJSON(job) }}
            };
            console.log(JSON.stringify(contexts, null, 2));

      - name: Install dotnet
        uses: actions/setup-dotnet@v2.1.0
        with:
          # renovate: datasource=docker depName=dotnet-sdk packageName=mcr.microsoft.com/dotnet/sdk
          dotnet-version: 6.0.400

      - name: Cake build
        run: dotnet tool restore && dotnet cake --target=info --verbosity=verbose

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Show contexts
        uses: actions/github-script@v6.1.1
        with:
          script: |
            // show contexts
            const contexts = {
              github: ${{ toJSON(github) }},
              runner: ${{ toJSON(runner) }},
              job: ${{ toJSON(job) }}
            };
            console.log(JSON.stringify(contexts, null, 2));

      - name: Install dotnet
        uses: actions/setup-dotnet@v2.1.0
        with:
          # renovate: datasource=docker depName=dotnet-sdk packageName=mcr.microsoft.com/dotnet/sdk
          dotnet-version: 6.0.400

      - name: Cake build
        run: dotnet tool restore && dotnet cake --target=info --verbosity=verbose
